title: Schema.org Blog
description: Schema.org Blogposts
baseurl: "schemablog" # the subpath of your site, e.g., /blog
url: "https://rvguha.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social Media
social:
  github: rvguha

# Custom settings
paginate: 5
paginate_path: "/page:num/"
